name: colony_game
description: A mobile colony-management survival builder (Banished-style).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
